name:                site
version:             0.1.0.0
github:              "osufpc/osufpc_website"
license:             BSD3
author:              "Jeffrey Young"
maintainer:          "functionalprogramming@oregonstate.edu"
copyright:           "2018 Jeffrey Young"

extra-source-files: []

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/temp#readme>

dependencies:
- base >= 4.7 && < 5
- hakyll == 4.9.*
- hjsmin == 0.2.*
- text
- turtle

library:
  source-dirs: []

executables:
  site:
    main:                site.hs
    source-dirs:         []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - site
